### ISSUE TITLE
replacement fee too low & processing response error

### ISSUE THREAD

**Issue by hanhan0427** [jerskisnow/Polygon-Arbitrage-Bot#3]
Error: replacement fee too low (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":73,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f90193818923849502f900849502f9148401312d0094657b7ce3ccae1a5c3d752934df5e3b565d248d6a80b9012432e9aa79000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff000000000000000000000000a1c57f48f0deb89f569dfbe6e2b7f46d33606fd40000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000c080a0ab9d5d65d014603430f259de337652ab192692992e5dbd7dafab56d5ad5ad902a061d06dcd33a604dd144263c2f6e8f6f799e2baeec6b05afca57d47bb875ba72c\"],\"id\":73,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://speedy-nodes-nyc.moralis.io/dc742e1f59eb82deebf6684a/polygon/mainnet"}, method="sendTransaction", transaction="0x02f90193818923849502f900849502f9148401312d0094657b7ce3ccae1a5c3d752934df5e3b565d248d6a80b9012432e9aa79000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff000000000000000000000000a1c57f48f0deb89f569dfbe6e2b7f46d33606fd40000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000c080a0ab9d5d65d014603430f259de337652ab192692992e5dbd7dafab56d5ad5ad902a061d06dcd33a604dd144263c2f6e8f6f799e2baeec6b05afca57d47bb875ba72c", code=REPLACEMENT_UNDERPRICED, version=providers/5.5.2)
    at Logger.makeError (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\logger\lib\index.js:199:21)
    at Logger.throwError (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\logger\lib\index.js:208:20)
    at checkError (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:111:16)
    at JsonRpcProvider.<anonymous> (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:659:47)
    at step (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'replacement fee too low',
  code: 'REPLACEMENT_UNDERPRICED',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":73,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f90193818923849502f900849502f9148401312d0094657b7ce3ccae1a5c3d752934df5e3b565d248d6a80b9012432e9aa79000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff000000000000000000000000a1c57f48f0deb89f569dfbe6e2b7f46d33606fd40000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000c080a0ab9d5d65d014603430f259de337652ab192692992e5dbd7dafab56d5ad5ad902a061d06dcd33a604dd144263c2f6e8f6f799e2baeec6b05afca57d47bb875ba72c\"],\"id\":73,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://speedy-nodes-nyc.moralis.io/dc742e1f59eb82deebf6684a/polygon/mainnet", code=SERVER_ERROR, version=web/5.5.1)
      at Logger.makeError (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\logger\lib\index.js:199:21)
      at Logger.throwError (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\logger\lib\index.js:208:20)
      at C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:301:32
      at step (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:33:23)
      at Object.next (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:14:53)
      at fulfilled (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"replacement transaction underpriced"}}\n',
    error: Error: replacement transaction underpriced
        at getResult (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:142:21)
        at processJsonFunc (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:344:22)
        at C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:276:46
        at step (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:33:23)
        at Object.next (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:14:53)
        at fulfilled (C:\Users\user\Downloads\Polygon-Arbitrage-Bot-main\Polygon-Arbitrage-Bot-main\node_modules\@ethersproject\web\lib\index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32000,
      data: undefined
    requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f90193818923849502f900849502f9148401312d0094657b7ce3ccae1a5c3d752934df5e3b565d248d6a80b9012432e9aa79000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff000000000000000000000000a1c57f48f0deb89f569dfbe6e2b7f46d33606fd40000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000c080a0ab9d5d65d014603430f259de337652ab192692992e5dbd7dafab56d5ad5ad902a061d06dcd33a604dd144263c2f6e8f6f799e2baeec6b05afca57d47bb875ba72c"],"id":73,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://speedy-nodes-nyc.moralis.io/dc742e1f59eb82deebf6684a/polygon/mainnet'
  },
  method: 'sendTransaction',
  transaction: {
    type: 2,
    chainId: 137,
    nonce: 35,
    maxPriorityFeePerGas: BigNumber { _hex: '0x9502f900', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x9502f914', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x01312d00', _isBigNumber: true },
    to: '0x657b7Ce3cCAe1a5C3d752934DF5e3b565D248d6a',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x32e9aa79000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a5e0829caced8ffdd4de3c43696c57f7d7a678ff000000000000000000000000a1c57f48f0deb89f569dfbe6e2b7f46d33606fd40000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010f0cf064dd59200000',
    accessList: [],
    hash: '0x1805d5703e1335d9a3806642871d78d57d079c7192f7f2429fce601d108ee46c',
    v: 0,
    r: '0xab9d5d65d014603430f259de337652ab192692992e5dbd7dafab56d5ad5ad902',
    s: '0x61d06dcd33a604dd144263c2f6e8f6f799e2baeec6b05afca57d47bb875ba72c',
    from: '0x8dcf0fC691Ff925F731Fe98fd4B7b8d1D149AC59',
    confirmations: 0
  },
  transactionHash: '0x1805d5703e1335d9a3806642871d78d57d079c7192f7f2429fce601d108ee46c'

Is it because the gas price is not set? 
Or is there anything I can change? Thanks

**Comment by OnlyF0uR** [comment]
It appears to be a pending transaction that got stuck in the mempool with a higher gas price. If you use alchemy or something alike you can check if there is an unmined transaction.

**Comment by hanhan0427** [comment]
Thanks for the reply, but the same error occurs even if I use my own RPC node, and the gas limit is set to the max value

**Comment by OnlyF0uR** [comment]
Then it might be related to the nonce not updating correctly. Does the problem occur when multiple arbitrage opportunities are found within one iteration?

**Comment by hanhan0427** [comment]
Yes, it seems that the nonce has no shift problem, but this happens in the single  arbitrage,it's weird

**Comment by hanhan0427** [comment]
ok,Problem solved, just use a different account.

Are you using the aave v1 protocol or v2?
The current operation has failed so far. Check that there is a problem in the call lendingpool.
![image](https://user-images.githubusercontent.com/22397149/159201890-a8542110-c9ef-4b35-9c57-ff4805207804.png)

**Comment by OnlyF0uR** [comment]
Okay, it uses Aave V2 right now, I have managed to test the individual swaps etc. However testing the actual flashloan is rather difficult. So if there is a problem then it must be related to the flashloan. It might also be related to the actual exchange rate slippage disallowing the contract from paying back the premium. I believe however that Aave V3 is out so I might take a look at that and review the contract once again. If anyone else wants to look at the code in the meanwhile upon reading this then feel free to. (https://github.com/jerskisnow/Polygon-Arbitrage-Contract)

**Comment by nervodatascience** [comment]
@hanhan0427  how did you solve the "fail" error in the transaction
